### ISSUE TITLE
Buggy Login

### ISSUE THREAD

**Issue by KatharineZhang** [aiillssa/Husky-Hustlers-Frontend#2]
Login still renders the HOmepage even if the user's email is NOT @uw.edu. In console, it says that when a user signs in without @uw.edu, login fails, but we still render the Homepage either way.

**Comment by KatharineZhang** [comment]
Now, it doesn't matter if you sign in with @uw.edu or a different one, it doesn't work. It always gives "Failed login". Sean believes it's because the database fails the login if it doesn't exist in the database.

**Comment by Sean0z** [comment]
- Added handling so that the user is not redirected to the homepage unless the login is successful. 
- The issue with the server always giving "failed login" was because the backend server was not running
