### ISSUE TITLE
URL's don't reset on refresh

### ISSUE THREAD

**Issue by KatharineZhang** [aiillssa/Husky-Hustlers-Frontend#3]
Case: When you've signed in and go to a page, but then refresh the page, it will route you to log in again. However, after you log in, instead of routing you to the homepage, it routes you to the previous page you were at because the URL didn't reset.

**Comment by Sean0z** [comment]
When you sign out and are redirected to the login page, the url now clears to just be the localhost address. And when you refresh the page without logging out, you stay logged in and are on the same page as before, which is intentional.
