### ISSUE TITLE
Images fail to load

### ISSUE THREAD

**Issue by planetquack1** [aiillssa/Husky-Hustlers-Frontend#5]
There is an image placeholder that shows an image icon and the file name. 
I'm not sure if this was intended as a placeholder, or the images are failing to render.
<img width="403" alt="Screenshot 2024-11-19 at 2 36 01 PM" src="https://github.com/user-attachments/assets/fbd29a10-a2b9-406f-a3c5-266e14ab99f8">

**Comment by KatharineZhang** [comment]
Those were placeholders. They are now solved and being displayed with a custom image component for banners, profile pics, and display icons.
