### ISSUE TITLE
Issues with search bar functionality

### ISSUE THREAD

**Issue by yyu2022-uw** [aiillssa/Husky-Hustlers-Frontend#7]
- The search function seems to have an issue. When I type a single letter (e.g., "c"), shop names that don’t contain that letter still appear in the results.
- The search bar filters shops immediately as I type, which might not be ideal. It could be better to trigger the search using a specific event (e.g., pressing "Enter" or clicking a search button).
- Clearing the search filter is inconvenient since I have to manually delete all text in the search bar. Additionally, if I click on a category while there’s text in the search bar, the filter still applies. I don't know if this behavior is intentional, but it might be better to automatically clear the search when a user interacts with other filters, like categories.

**Comment by aiillssa** [comment]
feedback addressed! :)
